"""Stable serialized enumerations for Omega's future command lifecycle."""

from __future__ import annotations

from enum import StrEnum


class IntentType(StrEnum):
    """Future command intents; values are stable machine-readable identifiers."""

    UNKNOWN = "unknown"
    HELP = "help"
    ACTIVATE_ASSISTANT = "activate_assistant"
    SHUTDOWN_ASSISTANT = "shutdown_assistant"
    OPEN_APPLICATION = "open_application"
    CLOSE_APPLICATION = "close_application"
    CHECK_APPLICATION_STATUS = "check_application_status"
    CREATE_FILE = "create_file"
    READ_FILE = "read_file"
    WRITE_FILE = "write_file"
    APPEND_FILE = "append_file"
    RENAME_FILE = "rename_file"
    COPY_FILE = "copy_file"
    MOVE_FILE = "move_file"
    DELETE_FILE = "delete_file"
    OPEN_FILE = "open_file"
    SEARCH_FILE = "search_file"
    CHECK_FILE_EXISTENCE = "check_file_existence"
    GET_FILE_INFORMATION = "get_file_information"
    CREATE_FOLDER = "create_folder"
    OPEN_FOLDER = "open_folder"
    LIST_FOLDER = "list_folder"
    RENAME_FOLDER = "rename_folder"
    COPY_FOLDER = "copy_folder"
    MOVE_FOLDER = "move_folder"
    DELETE_FOLDER = "delete_folder"
    CHECK_FOLDER_EXISTENCE = "check_folder_existence"
    GET_FOLDER_INFORMATION = "get_folder_information"
    SEARCH_FOLDER = "search_folder"
    UNDO_LAST_ACTION = "undo_last_action"
    SHOW_HISTORY = "show_history"
    CLEAR_HISTORY = "clear_history"
    EXPORT_HISTORY = "export_history"
    OPEN_BROWSER = "open_browser"
    CLOSE_BROWSER = "close_browser"
    OPEN_WEBSITE = "open_website"
    SEARCH_WEB = "search_web"
    OPEN_NEW_TAB = "open_new_tab"
    CLOSE_TAB = "close_tab"
    SWITCH_TAB = "switch_tab"
    LIST_TABS = "list_tabs"
    REFRESH_PAGE = "refresh_page"
    GO_BACK = "go_back"
    GO_FORWARD = "go_forward"
    GET_PAGE_INFORMATION = "get_page_information"
    FIND_TEXT_ON_PAGE = "find_text_on_page"
    OPEN_BOOKMARK = "open_bookmark"
    SAVE_BOOKMARK = "save_bookmark"
    GET_SYSTEM_INFORMATION = "get_system_information"
    GET_CPU_USAGE = "get_cpu_usage"
    GET_MEMORY_USAGE = "get_memory_usage"
    GET_DISK_USAGE = "get_disk_usage"
    GET_BATTERY_STATUS = "get_battery_status"
    GET_NETWORK_STATUS = "get_network_status"
    LIST_PROCESSES = "list_processes"
    SEARCH_PROCESS = "search_process"
    GET_PROCESS_INFORMATION = "get_process_information"
    GET_VOLUME = "get_volume"
    SET_VOLUME = "set_volume"
    INCREASE_VOLUME = "increase_volume"
    DECREASE_VOLUME = "decrease_volume"
    MUTE_VOLUME = "mute_volume"
    UNMUTE_VOLUME = "unmute_volume"
    GET_BRIGHTNESS = "get_brightness"
    SET_BRIGHTNESS = "set_brightness"
    INCREASE_BRIGHTNESS = "increase_brightness"
    DECREASE_BRIGHTNESS = "decrease_brightness"
    OPEN_WINDOWS_SETTINGS = "open_windows_settings"
    LOCK_COMPUTER = "lock_computer"
    SLEEP_COMPUTER = "sleep_computer"
    HIBERNATE_COMPUTER = "hibernate_computer"
    SIGN_OUT_USER = "sign_out_user"
    RESTART_COMPUTER = "restart_computer"
    SHUT_DOWN_COMPUTER = "shut_down_computer"
    CANCEL_POWER_ACTION = "cancel_power_action"
    CREATE_REMINDER = "create_reminder"
    CREATE_RECURRING_REMINDER = "create_recurring_reminder"
    LIST_REMINDERS = "list_reminders"
    SHOW_REMINDER = "show_reminder"
    UPDATE_REMINDER = "update_reminder"
    CANCEL_REMINDER = "cancel_reminder"
    COMPLETE_REMINDER = "complete_reminder"
    SNOOZE_REMINDER = "snooze_reminder"
    CREATE_ALARM = "create_alarm"
    CREATE_RECURRING_ALARM = "create_recurring_alarm"
    LIST_ALARMS = "list_alarms"
    SHOW_ALARM = "show_alarm"
    UPDATE_ALARM = "update_alarm"
    CANCEL_ALARM = "cancel_alarm"
    DISMISS_ALARM = "dismiss_alarm"
    SNOOZE_ALARM = "snooze_alarm"
    START_TIMER = "start_timer"
    PAUSE_TIMER = "pause_timer"
    RESUME_TIMER = "resume_timer"
    CANCEL_TIMER = "cancel_timer"
    SHOW_TIMER = "show_timer"
    LIST_TIMERS = "list_timers"
    LIST_SCHEDULED_ITEMS = "list_scheduled_items"
    CREATE_NOTE = "create_note"
    LIST_NOTES = "list_notes"
    SHOW_NOTE = "show_note"
    UPDATE_NOTE = "update_note"
    APPEND_NOTE = "append_note"
    SEARCH_NOTES = "search_notes"
    PIN_NOTE = "pin_note"
    UNPIN_NOTE = "unpin_note"
    ARCHIVE_NOTE = "archive_note"
    RESTORE_NOTE = "restore_note"
    DELETE_NOTE = "delete_note"
    TAG_NOTE = "tag_note"
    UNTAG_NOTE = "untag_note"
    EXPORT_NOTES = "export_notes"
    IMPORT_NOTES = "import_notes"
    CREATE_TASK_LIST = "create_task_list"
    LIST_TASK_LISTS = "list_task_lists"
    SHOW_TASK_LIST = "show_task_list"
    UPDATE_TASK_LIST = "update_task_list"
    ARCHIVE_TASK_LIST = "archive_task_list"
    RESTORE_TASK_LIST = "restore_task_list"
    DELETE_TASK_LIST = "delete_task_list"
    CREATE_TASK = "create_task"
    LIST_TASKS = "list_tasks"
    SHOW_TASK = "show_task"
    UPDATE_TASK = "update_task"
    COMPLETE_TASK = "complete_task"
    REOPEN_TASK = "reopen_task"
    CANCEL_TASK = "cancel_task"
    ARCHIVE_TASK = "archive_task"
    RESTORE_TASK = "restore_task"
    DELETE_TASK = "delete_task"
    SET_TASK_PRIORITY = "set_task_priority"
    SET_TASK_DEADLINE = "set_task_deadline"
    REMOVE_TASK_DEADLINE = "remove_task_deadline"
    MOVE_TASK = "move_task"
    TAG_TASK = "tag_task"
    UNTAG_TASK = "untag_task"
    SEARCH_TASKS = "search_tasks"
    SHOW_DUE_TASKS = "show_due_tasks"
    SHOW_OVERDUE_TASKS = "show_overdue_tasks"
    LINK_TASK_REMINDER = "link_task_reminder"
    UNLINK_TASK_REMINDER = "unlink_task_reminder"
    CREATE_KNOWLEDGE_COLLECTION = "create_knowledge_collection"
    LIST_KNOWLEDGE_COLLECTIONS = "list_knowledge_collections"
    SHOW_KNOWLEDGE_COLLECTION = "show_knowledge_collection"
    UPDATE_KNOWLEDGE_COLLECTION = "update_knowledge_collection"
    ARCHIVE_KNOWLEDGE_COLLECTION = "archive_knowledge_collection"
    RESTORE_KNOWLEDGE_COLLECTION = "restore_knowledge_collection"
    DELETE_KNOWLEDGE_COLLECTION = "delete_knowledge_collection"
    IMPORT_KNOWLEDGE_DOCUMENT = "import_knowledge_document"
    LIST_KNOWLEDGE_DOCUMENTS = "list_knowledge_documents"
    SHOW_KNOWLEDGE_DOCUMENT = "show_knowledge_document"
    MOVE_KNOWLEDGE_DOCUMENT = "move_knowledge_document"
    REINDEX_KNOWLEDGE_DOCUMENT = "reindex_knowledge_document"
    REMOVE_KNOWLEDGE_DOCUMENT = "remove_knowledge_document"
    SEARCH_KNOWLEDGE = "search_knowledge"
    ASK_KNOWLEDGE = "ask_knowledge"
    SHOW_KNOWLEDGE_SOURCES = "show_knowledge_sources"
    EXPORT_KNOWLEDGE_RESULTS = "export_knowledge_results"


class ActionStatus(StrEnum):
    """Lifecycle states for an action proposal or its later execution."""

    PENDING = "pending"
    AWAITING_CONFIRMATION = "awaiting_confirmation"
    APPROVED = "approved"
    REJECTED = "rejected"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"
    SKIPPED = "skipped"
    ROLLED_BACK = "rolled_back"
    PARTIALLY_COMPLETED = "partially_completed"


class RiskLevel(StrEnum):
    """Risk levels from reversible operations through prohibited ones."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class PermissionDecision(StrEnum):
    """A future safety policy's authorization decision."""

    ALLOW = "allow"
    REQUIRE_CONFIRMATION = "require_confirmation"
    DENY = "deny"


class ConfirmationStatus(StrEnum):
    """The current state of a user-confirmation requirement."""

    NOT_REQUIRED = "not_required"
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXPIRED = "expired"


class EntityType(StrEnum):
    """Kinds of values a future command-understanding layer may extract."""

    APPLICATION = "application"
    FILE = "file"
    FOLDER = "folder"
    PATH = "path"
    FILE_NAME = "file_name"
    FOLDER_NAME = "folder_name"
    FILE_EXTENSION = "file_extension"
    LOCATION = "location"
    TEXT_CONTENT = "text_content"
    SEARCH_QUERY = "search_query"
    BOOLEAN = "boolean"
    NUMBER = "number"
    DURATION = "duration"
    URL = "url"
    TAB = "tab"
    BOOKMARK = "bookmark"
    WEB_QUERY = "web_query"
    PERCENTAGE = "percentage"
    PROCESS = "process"
    SETTINGS_PAGE = "settings_page"
    POWER_ACTION = "power_action"
    SCHEDULE = "schedule"
    DATE_TIME = "date_time"
    NOTE = "note"
    TASK = "task"
    TASK_LIST = "task_list"
    TAG = "tag"
    PRIORITY = "priority"
    KNOWLEDGE_COLLECTION = "knowledge_collection"
    KNOWLEDGE_DOCUMENT = "knowledge_document"
    KNOWLEDGE_SOURCE = "knowledge_source"
    UNKNOWN = "unknown"


class ErrorCategory(StrEnum):
    """Categories for serializable error records."""

    VALIDATION = "validation"
    CONFIGURATION = "configuration"
    PARSING = "parsing"
    PERMISSION = "permission"
    SAFETY = "safety"
    NOT_FOUND = "not_found"
    ALREADY_EXISTS = "already_exists"
    EXECUTION = "execution"
    TIMEOUT = "timeout"
    CANCELLED = "cancelled"
    UNSUPPORTED = "unsupported"
    INTERNAL = "internal"


class CommandSource(StrEnum):
    """Future sources of a command without embedding source-specific objects."""

    TEXT = "text"
    VOICE = "voice"
    SYSTEM = "system"
    SCHEDULED = "scheduled"
